global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'product_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8082']
        labels:
          application: 'Product Service App'

  - job_name: 'order_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order-service:8084' ]
        labels:
          application: 'Order Service App'

  - job_name: 'office_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'office-service:8081' ]
        labels:
          application: 'Office Service App'

  - job_name: 'jwt_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'jwt-service:8091' ]
        labels:
          application: 'Jwt Service App'
