apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'office_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'office-service:8081' ]
            labels:
              application: 'Office Service App'
      - job_name: 'product_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['product-service:8082']
            labels:
              application: 'Product Service App'

      - job_name: 'order_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'order-service:8084' ]
            labels:
              application: 'Order Service App'
      - job_name: 'jwt_service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: [ 'jwt-service:8091' ]
            labels:
              application: 'Jwt Service App'

  mysql-server: mysql
  mysql-database-name: mysql-k8t
  mysql-user-name: root
