apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-app
  namespace: monitoring
  labels:
    app: gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      containers:
        - name: gateway-app
          image: javenockdocker/gateway-svc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: gateway-app
  ports:
    - protocol: TCP
      name: http
      port: 8085
      targetPort: 8085
      nodePort: 30003
