apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-service
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: office-service
  template:
    metadata:
      labels:
        app: office-service
    spec:
      containers:
        - name: app
          image: javenockdocker/office-svc
          ports:
            - containerPort: 8081
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/animal
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: office-service
  namespace: monitoring
spec:
  selector:
    app: office-service
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
