apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-svc-application
  template:
    metadata:
      labels:
        app: product-svc-application
    spec:
      containers:
        - name: spring-crud-app
          image: javenockdocker/product-svcc
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: product-svc-application
  ports:
    - protocol: 'TCP'
      port: 8082
      targetPort: 8082
