apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-k8t-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-k8t-application
  template:
    metadata:
      labels:
        app: orders-k8t-application
    spec:
      containers:
        - name: orders-crud-app
          image: javenockdocker/orders-svc123
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: prometheus-server-conf
                  key: mysql-server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: prometheus-server-conf
                  key: mysql-database-name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: prometheus-server-conf
                  key: mysql-user-name
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: orders-k8t-application
  ports:
    - protocol: 'TCP'
      port: 8084
      targetPort: 8084
