apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: monitoring
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: '2181'
            - name: ZOOKEEPER_TICK_TIME
              value: '2000'
          image: wurstmeister/zookeeper
          name: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: monitoring
  labels:
    app: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
status:
  loadBalancer: {}
