server:
  port: 8091

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:~/login
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  application:
    name: LOGIN-SERVICE

bezkoder:
  app:
    jwtSecret : bezKoderSecretKey
    jwtExpirationMs : 86400000
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: prometheus


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

#bezkoder:
#  app:
#    jwtSecret : bezKoderSecretKey
#    jwtExpirationMs : 86400000
