server:
  port: 8082
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 19pool90
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  application:
    name: PRODUCT-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true


